//  Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: mongodb-intro
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2019-12-12
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to create a microservice with MongoDB and Open Liberty.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE', MongoDB]
:page-related-guides: [???]
:page-permalink: /guides/{projectid}
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Building a microservice with MongoDB

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to store data with MongoDB using CDI and MicroProfile Config.

== What you'll learn

You will learn how to build and test a simple microservice with MongoDB, which will expose
the crew member's information. The service will respond to `POST`, `PUT` and `DELETE` requests made to the `\http://localhost:9080/mongo/crew` URL.

The microservice also responds to a `GET` request with a JSON representation of the crew members information, where
each property is a field in a JSON object like this:

[source,json,role="no_copy"]
----
[
  {
    "_id": {
      "$oid": "5dee6b079503234323db2ebc"
    },
    "Name": "Member1",
    "Rank": "Captain",
    "CrewID": "000001"
  },
  {
    "_id": {
      "$oid": "5dee6b079503234323db2ebd"
    },
    "Name": "Member2",
    "Rank": "Engineer",
    "CrewID": "000002"
  }
]
----

This application uses a CDI producer to inject a MongoDatabase and MicroProfile Config makes configuring MongoDB driver simple.


// =================================================================================================
// Additional prerequisites
// =================================================================================================

== Additional prerequisites

Before you begin, you must install MongoDB onto your machine and setup a new database for the microservice.

=== MongoDB installation 

If you already have MongoDB installed and running on your system, you can skip to the `Database setup` section.

If you have Docker, you can execute the following commands to run a mongo image in a Docker container:

[role='command']
```
docker pull mongo
docker run --name mongo-sample -p 127.0.0.1:27017:27017 -d mongo
```

If you do not have Docker, you can install MongoDB manually for your operating system from the official https://docs.mongodb.com/manual/administration/install-community/[MongoDB website].

=== Database setup

You will need to create a new database and a user for authentication. If you are using Docker, access the container's command line by running the following command:

[role='command']
```
docker exec -it mongo-sample bash
```

Issue the following commands to enter the mongo Shell, create a new database, and create a new user for the database:

[role='command']
```
mongo
use testdb
db.createUser({user: 'sampleUser', pwd:'openliberty', roles: [{ role: 'readWrite', db:'testdb'}]})
```

See https://docs.mongodb.com/manual/mongo/index.html[The mongo Shell] for more information about the using their Shell.

Type `exit` to get out of the mongo Shell, and if you are using Docker, type `exit` again to leave the Docker Shell.

// =================================================================================================
// Getting Started
// =================================================================================================

[role='command']
include::{common-includes}/gitclone.adoc[]


=== No need for a MongoDB feature

In the past, using MongoDB required enabling the `mongodb-2.0` feature, which was limited to certain MongoDB 2.X versions. By using a CDI producer, any version of MongoDB can be used, with no need for a specific MongoDB feature. Even if the MongoDB Java Driver API changes, simple updates to your CDI producer will allow it to continue to work. 

The MongoDB driver should be bundled in your application. To do this with Maven you can use a dependency:

[source,role="no_copy"]
----
<dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>mongo-java-driver</artifactId>
    <version>X.X.X</version>
</dependency>
----

If you have multiple applications accessing MongoDB, instead of bundling the MongoDB driver, you can configure a shared library in your `server.xml` like this:

[source,role="no_copy"]
----
<library id="MongoLib">
    <file name="${shared.resource.dir}/mongo-java-driver-3.8.0.jar" />
</library>

<webApplication location="MongoDBSample1.war">
    <classloader commonLibraryRef="MongoLib" />
</webApplication>

<webApplication location="MongoDBSample2.war">
    <classloader commonLibraryRef="MongoLib" />
</webApplication>
----

// =================================================================================================
// Try what you'll build
// =================================================================================================

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.

To try out the application, first go to the `finish` directory and run the following Maven 
goal to build the application and deploy it to Open Liberty:
[role='command']
```
mvn liberty:run
```

Check out the application at the
http://localhost:9080/mongo[^] URL.

After you are done checking out the application, stop the Open Liberty server by pressing `CTRL+C`
in the shell session where you ran the server. Alternatively, you can run the `liberty:stop` goal 
from the `finish` directory in another shell session:

[role='command']
```
mvn liberty:stop
```

// =================================================================================================
// Creating a microservice which stores data to MongoDB
// =================================================================================================

== Creating a microservice which stores data to MongoDB

Navigate to the `start` directory to begin.

Start Open Liberty in development mode, which starts the Open Liberty server and listens 
for file changes:

[role="command"]
```
mvn liberty:dev
```

// =================================================================================================
// Configuring the server
// =================================================================================================

== Configuring the server

To get the service running, the Liberty server needs to be correctly configured.

[role="code_command hotspot", subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The configuration does the following actions:

. Configures the server to enable JAX-RS. This is specified in the [hotspot=featureManager file=0]`featureManager` element.
. Configures the server to resolve the HTTP port numbers from variables, which are then specified in
the Maven [hotspot=defaultHttpPort hotspot=defaultHttpsPort file=1]`pom.xml` file. This is specified in the [hotspot=httpEndpoint file=0]`<httpEndpoint/>` element. Variables use the `${variableName}` syntax.
. Configures the server to run the produced microservice on a context root specified in the 
[hotspot=appContextRoot file=1]`pom.xml` file. This is specified in the [hotspot=webApplication file=0]`<webApplication/>` element.

pom.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/pom.xml[]
----

The variables that are being used in the [hotspot=httpEndpoint hotspot=webApplication file=0]`server.xml` file are provided by the properties set in the Maven [hotspot=defaultHttpPort hotspot=defaultHttpsPort hotspot=appContextRoot file=1]`pom.xml` file.


// =================================================================================================
// Creating a CDI Producer for Mongo
// =================================================================================================

== Creating a CDI Producer for Mongo

With a CDI producer, you are no longer restricted to MongoDB 2.X versions, and can easily provide a `MongoDatabase` to your application. 

[role="code_command hotspot", subs="quotes"]
----
#Create the `MongoProducer` class.#
`src/main/java/io/openliberty/guides/mongo/MongoProducer.java`
----

MongoProducer.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/mongo/MongoProducer.java[]
----

=== Configuring with MicroProfile Config

Using MicroProfile Config makes configuring the MongoDB driver simple.

[role="code_command hotspot", subs="quotes"]
----
#Create the configuration file.#
`src/main/webapp/META-INF/microprofile-config.properties`
----

microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/webapp/META-INF/microprofile-config.properties[]
----

MongoProducer.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/mongo/MongoProducer.java[]
----

pom.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/pom.xml[]
----

server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The values in the [hotspot file=0]`microprofile-config.properties` file are injected into the [hotspot=mongoProducerInjections file=1]`MongoProducer` class.

=== Using an encoded password with passwordUtilities-1.0

One of the advantages of using a CDI producer is that it can be tailored to your needs. For improved security, the [hotspot=createMongo file=1]`createMongo` method includes authentication with a [hotspot=username file=1]`user name` and an [hotspot=encodedPassword file=1]`encoded password` which is decoded using [hotspot=passwordUtil file=1]`passwordUtilities-1.0`. 

This tool is included in `pom.xml` as a [hotspot=passwordUtilDependency file=2]`dependency` and added to `server.xml` as a [hotspot=passwordUtilFeature file=3]`feature`.

// =================================================================================================
// Basic CRUD operations
// =================================================================================================

== Basic CRUD operations

You will be implementing the basic `CRUD` operations which are `CREATE`, `READ`, `UPDATE`, and `DELETE`. The http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/package-summary.html[com.mongodb.client] package is used help to implement these `CRUD` operations for the microservice. The http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/MongoDatabase.html#getCollection(java.lang.String)[MongoDatabase.getCollection()] method will be used to get the http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/MongoCollection.html[MongoCollection] and several methods from http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/MongoCollection.html[MongoCollection] will be used to interact with the collection to implement the `CRUD` operations.

See https://openliberty.io/guides/rest-intro.html[Creating a RESTful web serivce] for more information about creating a REST service with JAX-RS, JSON-B, and Open Liberty.

[role="code_command hotspot", subs="quotes"]
----
#Modify the `CrewService` class.#
`src/main/java/io/openliberty/guides/application/CrewService.java`
----

CrewService.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/application/CrewService.java[]
----

CrewMember.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/application/CrewMember.java[]
----

A [hotspot=beanValidator]`Validator` is used to validate the [hotspot=crewMember file=1]`CrewMember` before inserting or updating the database.

=== Injecting the database

The CDI producer is used to inject a [hotspot=dbInjection]`MongoDatabase` into the [hotspot file=0]`CrewService` class.

=== Create
The http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/MongoCollection.html#insertOne-TDocument-[MongoCollection.insertOne()] method is used to insert a new document into the collection. This method takes in a `TDocument` which is the configuration of the new crew member to be inserted into the collection and does not return anything. The [hotspot=create]`add()` method handles the implementation of `CREATE`.

Test the `CREATE` endpoint by running the following cURL command:
[role='command']
```
curl http://localhost:9080/mongo/crew/000003 -d"{\"name\": \"Member3\",\"crewID\": \"000003\", \"rank\":\"Officer\"}" -H "Content-Type:application/json" -H "Accept: application/json" -X POST
```

You will receive a response containing the JSON object of the new member.

```
{
  "_id": {
    "$oid": "<<ID>>"
  },
  "Name": "Member3",
  "Rank": "Officer",
  "CrewID": "000003"
}
```


=== Read
The http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/MongoCollection.html#find--[MongoCollection.find()] method is used to retrieve an iterable of all the crew member documents in the collection. This method does not take in any arguments and returns a http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/FindIterable.html[FindIterable] object. The [hotspot=read]`retrieve()` method handles the implementation of `READ`.

Test the `READ` endpoint by running the following cURL command:
[role='command']
```
curl http://localhost:9080/mongo/crew -X GET
```

You will receive a response containing an array of all the members currently in your crew.

```
[
  {
    "_id": {
      "$oid": "<<ID>>"
    },
    "Name": "Member3",
    "Rank": "Officer",
    "CrewID": "000003"
  }
]
```

=== Update
The http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/MongoCollection.html#replaceOne-org.bson.conversions.Bson-TDocument-[MongoCollection.replaceOne()] method is used update a specified document. This method takes in a `Bson` which contains the `id` of the document to be replaced and another `TDocument` which is the new configuration of the crew member. The method returns an http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/result/UpdateResult.html[UpdateResult] object with a method called `getMatchedCount()` which indicates the number of matches to the query. The [hotspot=update]`update()` method handles the implementation of `UPDATE`.

Test the `UPDATE` endpoint by running the following cURL command:
[role='command']
```
curl http://localhost:9080/mongo/crew/<<ID>> -d"{\"name\": \"Member3New\",\"crewID\": \"000003\", \"rank\":\"Officer\"}" -H "Content-Type:application/json" -H "Accept: application/json" -X PUT
```

You will receive a reponse containing the JSON object of the updated member.

```
{
  "Name": "Member3New",
  "Rank": "Officer",
  "CrewID": "000003"
}
```

=== Delete
The http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/MongoCollection.html#deleteOne-org.bson.conversions.Bson-[MongoCollection.deleteOne()] method is used to remove a document from the collection. This method takes in a `Bson` which contains the `id` of the document to be deleted and returns a http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/result/DeleteResult.html[DeleteResult] object with a method called `getDeletedCount()` to indicate the number of documents deleted from the collection. The [hotspot=delete]`remove()` method handles the implementation of `DELETE`.

Test the `DELETE` endpoint by running the following cURL command:
[role='command']
```
curl http://localhost:9080/mongo/crew/<<ID>> -X DELETE
```

You will receive a response containing the id of the deleted crew member.

```
{
  "_id": {
    "$oid": "<<ID>>"
  }
}
```

// =================================================================================================
// Building and running the application
// =================================================================================================

== Building and running the application

The Open Liberty server was started in development mode at the beginning of the guide and all the 
changes were automatically picked up.

Check out the service that you created at the
http://localhost:9080/mongo[^] URL. 

// =================================================================================================
// Testing the service
// =================================================================================================

== Testing the service

You can test this microservice manually by sending HTTP requests to http://localhost:9080/mongo/crew[^] or by starting a server and pointing a web browser at the
http://localhost:9080/mongo[^] URL. Automated tests are a much better
approach because they trigger a failure if a change introduces a bug. JUnit and the JAX-RS Client
API provide a simple environment to test the application.

You can write tests to call the application server directly.

[role="code_command hotspot", subs="quotes"]
----
#Create the `CrewApplicationEndpointIT` class.#
`src/test/java/it/io/openliberty/guides/application/CrewApplicationEndpointIT.java`
----

CrewApplicationEndpointIT.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/test/java/it/io/openliberty/guides/application/CrewApplicationEndpointIT.java[]
----

This test class has more lines of code than the resource implementation.
The test method is indicated with the [hotspot=test file=0]`@Test` annotation.

pom.xml
[source , xml, linenums,role="code_column hide_tags=copyright"]
----
include::finish/pom.xml[]
----

The test code needs to know some information about the application to make requests. The server port and the application context root are key, and are dictated by the server configuration. While this information can be hardcoded, it is better to specify it in a single place like the Maven [hotspot=defaultHttpPort hotspot=appContextRoot file=1]`pom.xml` file. Refer to the [hotspot file=1]`pom.xml` file to see how the application information such as the [hotspot=defaultHttpPort file=1]`http.port` and [hotspot=appContextRoot file=1]`default.app.context.root` elements are provided in the file.


These Maven properties are then passed to the Java test program as the [hotspot=testsysprops file=1]`<systemPropertyVariables/>` element in the [hotspot file=1]`pom.xml` file.

The [hotspot=Before file=0]`@Before` annotation is placed on a method that runs before any of the test cases. In this case, the method creates a JAX-RS client, which makes HTTP requests to the crew service, it also retrieves the port number and application context for the Open Liberty server, creates testing crew member data and builds a base URL string that is used throughout the tests.

The [hotspot=After file=0]`@After` with [hotspot=teardown file=0]`teardown()` method simply destroys the client instance.

See the following descriptions of the test cases:

* [hotspot=testAddCrewMember file=0]`testAddCrewMember()` verifies that new members are correctly added to the database.

* [hotspot=testUpdateCrewMember file=0]`testUpdateCrewMember()` verifies that a crew member information is correctly updated.

* [hotspot=testGetCrewMembers file=0]`testGetCrewMembers()` verifies that a list of crew members returned by the application API.

* [hotspot=testDeleteCrewMember file=0]`testDeleteCrewMember()` verifies that the crew members are correctly removed from the database.

=== Running the tests

Since you started Open Liberty in development mode at the start of the guide, press
`enter/return` key to run the tests. You will see the following output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.application.CrewApplicationEndpointIT
   === Adding 2 members to the database. ===
      === Done. ===
   === Updating crew member with id 5df7e2711d2a091f901e8c1b. ===
      === Done. ===
   === Listing crew members from the database. ===
      === Done. There are 4 members. ===
   === Removing 2 members from the database. ===
      === Done. ===
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.842 s - in it.io.openliberty.guides.application.CrewApplicationEndpointIT
Results:
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, add an assertion that you know fails, or change the existing
assertion to an unexpected constant value.

When you are done checking out the application, exit development mode by typing `q` in the shell session where
you ran the server and then pressing the `enter/return` key.


== Great work! You're done!

You developed a microservice in Open Liberty by using MongoDB, JAX-RS and JSON-B.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]