//  Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: mongodb-intro
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2019-12-12
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to store data with MongoDB using Contexts and Dependency Injection (CDI) and MicroProfile Config.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE', 'MongoDB']
:page-related-guides: ['rest-intro', 'cdi-intro']
:page-permalink: /guides/{projectid}
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Building a microservice with MongoDB

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to store data with `MongoDB` using Contexts and Dependency Injection (CDI) and MicroProfile Config.

== What you'll learn

You will learn how to build and test a simple microservice which manages the members of a crew using `MongoDB`. The microservice will respond to `POST`, `GET`, `PUT`, and `DELETE` requests made to the service to manipulate the database.

The crew members will be stored in `MongoDB` in JSON documents in this format:

[source,json,role="no_copy"]
----
{
  "_id": {
    "$oid": "5dee6b079503234323db2ebc"
  },
  "Name": "Member1",
  "Rank": "Captain",
  "CrewID": "000001"
}
----

This microservice connects to `MongoDB` using TLS by using a CDI producer to inject a `MongoDatabase` and MicroProfile Config to make configuring the `MongoDB` driver simple. 

For more information about using a CDI producer and MicroProfile Config, see https://openliberty.io/guides/cdi-intro.html[Injecting dependencies into microservices] and https://openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices].

// =================================================================================================
// Getting Started
// =================================================================================================

[role='command']
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Setting up MongoDB
// =================================================================================================

== Setting up MongoDB

This guide will use Docker to run an instance of `MongoDB` for a fast setup. A multi-stage Dockerfile is provided which uses the `mongo` image as the final stage's base image and will gather the required configuration files. Then, the resulting `mongo` image will be run in a Docker container and you will need to setup a new database for the microservice. Lastly, the truststore generated in the Docker image will be copied from the container and placed into the Open Liberty server.

=== The MongoDB configuration

mongodb.conf
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::assets/mongodb.conf[]
----

The `mongodb.conf` file specifies the `MongoDB` configuration `mongod`, the `MongoDB` daemon, should use. A sample configuration file is provided which sets up [hotspot=net]`net` to use TLS. Additional configuration options can be found in the official https://docs.mongodb.com/manual/reference/configuration-options/[MongoDB website].

=== The Dockerfile

Dockerfile
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::Dockerfile[]
----

The [hotspot=stageOne file=0]`first stage` of the Dockerfile uses the [hotspot=openLiberty file=0]`open-liberty` image as the base image to create a [hotspot=selfSignedCert file=0]`self-signed certificate` and [hotspot=privateKey file=0]`private key` which are concatenated together to generate the [hotspot=catCerts file=0]`mongodb_tls.pem` file used for TLS. Then, it uses the Java [hotspot=keytool file=0]`keytool` to generate the truststore and adds the certificate file to the truststore. The [hotspot=stageTwo file=0]`second stage` of the Dockerfile uses the [hotspot=mongo file=0]`mongo` image as the base image and copies over the generated files from the [hotspot=stageOne hotspot=copyCerts file=0]`first stage`. Additionally, it copies the [hotspot=copyConfig]`mongodb.conf` configuration file from your host machine to the image.

=== Running MongoDB in a Docker container

Execute the following commands to build the image using the Dockerfile, run it in a Docker container, specify the `MongoDB` configuration `mongod` (the `MongoDB` daemon) should use, and map port 27017 from the container to your host machine:

[role='command']
```
docker build -t mongo-sample .
docker run --name mongo-guide -p 127.0.0.1:27017:27017 -d mongo-sample --config etc/mongodb/mongodb.conf
```

=== Database setup

You will need to create a new database and a new user for authentication through the `mongo` Shell.

Access the Docker container's command line by running the following command:

[role='command']
```
docker exec -it mongo-guide bash
```

Issue the following commands to enter the `mongo` Shell, create a new database, and create a new user for the database:

[role='command']
```
mongo --tls --tlsCAFile /etc/mongodb/cert.pem --host localhost
use testdb
db.createUser({user: 'sampleUser', pwd:'openliberty', roles: [{ role: 'readWrite', db:'testdb'}]})
```

See https://docs.mongodb.com/manual/mongo/index.html[The mongo Shell] for more information about the using their Shell.

Type `exit` to get out of the `mongo` Shell, and type `exit` again to leave the Docker Shell.

=== Adding the truststore to the Open Liberty Server

Execute the following commands to copy `truststore.p12` from the container to the correct location in the start and finish directories on your host machine:

include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section]
--
[role='command']
```
docker cp mongo-guide:/etc/mongodb/truststore.p12 start/src/main/liberty/config/resources/security
copy start/src/main/liberty/config/resources/security/truststore.p12 finish/src/main/liberty/config/resources/security/
```
--

[.tab_content.mac_section]
--
[role='command']
```
docker cp mongo-guide:/etc/mongodb/truststore.p12 start/src/main/liberty/config/resources/security
cp start/src/main/liberty/config/resources/security/truststore.p12 finish/src/main/liberty/config/resources/security/
```
--

[.tab_content.linux_section]
--
[role='command']
```
docker cp mongo-guide:/etc/mongodb/truststore.p12 start/src/main/liberty/config/resources/security
cp start/src/main/liberty/config/resources/security/truststore.p12 finish/src/main/liberty/config/resources/security/
```
--

// =================================================================================================
// Try what you'll build
// =================================================================================================

== Try what you'll build

The `finish` directory in the root of this guide contains the finished microservice. Give it a try before you proceed.

To try out the application, first go to the `finish` directory and run the following Maven 
goal to build the application and deploy it to Open Liberty:
[role='command']
```
mvn liberty:run
```

If you see `The MongoServer server is ready to run a smarter planet. The MongoServer server started in 4.300 seconds.` in the console, then it is ready for you to check out the microservice through the web interface at the http://localhost:9080/mongo/[^] URL.

After you are done checking out the microservice, stop the Open Liberty server by pressing `CTRL+C`
in the shell session where you ran the server. Alternatively, you can run the `liberty:stop` goal 
from the `finish` directory in another shell session:

[role='command']
```
mvn liberty:stop
```

// =================================================================================================
// Server configuration
// =================================================================================================

== Server configuration

server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The Open Liberty server configuration defines the following settings:

. Configures the server to enable JAX-RS. This is specified in the [hotspot=featureManager file=0]`featureManager` element.
. Configures the server to resolve the HTTP port numbers from variables, which are then specified in
the Maven [hotspot=defaultHttpPort hotspot=defaultHttpsPort file=1]`pom.xml` file. This is specified in the [hotspot=httpEndpoint file=0]`<httpEndpoint/>` element. Variables use the `${variableName}` syntax.
. Configures the server to run the produced microservice on a context root specified in the 
[hotspot=appContextRoot file=1]`pom.xml` file. This is specified in the [hotspot=webApplication file=0]`<webApplication/>` element.
. Sets up the [hotspot=sslContext file=0]`SSL context` in order to connect to `MongoDB` using TLS.

pom.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/pom.xml[]
----

The variables that are being used in the [hotspot=httpEndpoint hotspot=webApplication file=0]`server.xml` file are provided by the properties set in the Maven [hotspot=defaultHttpPort hotspot=defaultHttpsPort hotspot=appContextRoot file=1]`pom.xml` file.

**No need for a MongoDB feature**

In the past, using `MongoDB` required enabling the `mongodb-2.0` feature, which was limited to certain MongoDB 2.X versions. By using a CDI producer, any version of MongoDB can be used, with no need for a specific MongoDB feature. Even if the MongoDB Java Driver API changes, simple updates to your CDI producer will allow it to continue to work. 

The `MongoDB` driver should be bundled in your microservice in your [hotspot=mongoDriver file=1]`pom.xml`.

// =================================================================================================
// Starting the Open Liberty server in development mode
// =================================================================================================

== Starting the Open Liberty server in development mode

Navigate to the `start` directory to begin.

[role='command']
include::{common-includes}/devmode-start.adoc[]

// =================================================================================================
// Creating a CDI Producer for Mongo
// =================================================================================================

== Creating a CDI Producer for Mongo

With a CDI producer, you are no longer restricted to `MongoDB` 2.X versions, and can easily provide a `MongoDatabase` to your microservice. 

[role="code_command hotspot", subs="quotes"]
----
#Create the `MongoProducer` class.#
`src/main/java/io/openliberty/guides/mongo/MongoProducer.java`
----

MongoProducer.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/mongo/MongoProducer.java[]
----

**Configuring with MicroProfile Config**

Using MicroProfile Config makes configuring the `MongoDB` driver simple.

microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/webapp/META-INF/microprofile-config.properties[]
----

pom.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/pom.xml[]
----

server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The values in the [hotspot file=1]`microprofile-config.properties` file are injected into the [hotspot=mongoProducerInjections file=0]`MongoProducer` class.

**Using an encoded password with passwordUtilities-1.0**

One of the advantages of using a CDI producer is that it can be tailored to your needs. For improved security, the [hotspot=createMongo file=0]`createMongo()` method includes authentication with a [hotspot=username file=0]`user name` and an [hotspot=encodedPassword file=0]`encoded password` which is decoded using [hotspot=passwordUtil file=0]`passwordUtilities-1.0`. 

This tool is included in [file=2]`pom.xml` as a [hotspot=passwordUtilDependency file=2]`dependency` and added to `server.xml` as a [hotspot=passwordUtilFeature file=3]`feature`.

**Using TLS**

Since you started your `MongoDB` server using TLS, you must setup the SSL context in your Open Liberty server accordingly. The `ssl` dependency is imported in the [hotspot=sslDependency file=2]`pom.xml` and enabled in the [hotspot=sslFeature file=3]`server.xml`. Additionally, the SSL context is setup in the [hotspot=sslContext file=3]`server.xml` to use the `TLS` protocol, the default keystore and your truststore which contains the public key. In your [hotspot file=1]`MongoProducer`, the [hotspot=sslContext file=1]`SSL context` is retrieved using the `JSSEHelper` and it is included in the [hotspot=sslEnable file=1]`MongoClientOptions`.

// =================================================================================================
// Basic CRUD operations
// =================================================================================================

== Basic CRUD operations

You will be implementing the basic `CRUD` operations which are `CREATE`, `READ`, `UPDATE`, and `DELETE`. The [hotspot=mongoImports]`com.mongodb.client` package is used to help implement these `CRUD` operations for the microservice. For more information about this package, see the https://mongodb.github.io/mongo-java-driver/3.12/javadoc/com/mongodb/client/package-summary.html[com.mongodb.client Javadocs].

See https://openliberty.io/guides/rest-intro.html[Creating a RESTful web serivce] for more information about creating a REST service with JAX-RS, JSON-B, and Open Liberty.

[role="code_command hotspot", subs="quotes"]
----
#Replace the `CrewService` class.#
`src/main/java/io/openliberty/guides/application/CrewService.java`
----

CrewService.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/application/CrewService.java[]
----

CrewMember.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/application/CrewMember.java[]
----

A [hotspot=beanValidator]`Validator` is used to validate the [hotspot=crewMember file=1]`CrewMember` using the [hotspot=getViolations]`getViolations()` method before [hotspot=violations1]`inserting` or [hotspot=violations2]`updating` the database.

=== Injecting the database

The CDI producer is used to inject a [hotspot=dbInjection]`MongoDatabase` into the [hotspot file=0]`CrewService` class.

Visit http://localhost:9080/openapi/ui/[^] to test and see the API documentation for the next sections.

=== Create

The [hotspot=add]`add()` method handles the implementation of `CREATE`. An instance of `MongoCollection` is retrieved by invoking [hotspot=getCollection]`MongoDatabase.getCollection()` method and specifying the `Crew` collection. The `MongoCollection<TDocument>` is a generic with a `TDocument` type parameter and the [hotspot=bsonDocument]`Document` class will be used as the `TDocument` type for this guide. The crew member is converted to a [hotspot=createCrewMember]`Document` and the [hotspot=insertOne]`MongoCollection.insertOne()` method is called to insert the new crew member `Document`.

Test the `CREATE` operation through the OpenAPI UI at the `POST /api/crew` endpoint with the following as the request body:
```
{
  "name": "Member1",
  "rank": "Officer",
  "crewID": "000001"
}
```

This will create a new document in the `Crew` collection with a Name of `Member1`, Rank of `Officer`, and CrewID of `000001`.

You will receive a response containing the JSON object of the new member.

```
{
  "_id": {
    "$oid": "<<ID>>"
  },
  "Name": "Member1",
  "Rank": "Officer",
  "CrewID": "000001"
}
```

The `\<<ID>>` is a unique identifier in the collection. Save this value for future commands.

=== Read

The [hotspot=retrieve]`retrieve()` method handles the implementation of `READ`. Firstly the `Crew` collection is retrieved using [hotspot=getCollectionRead]`MongoDatabase#getCollection`. The [hotspot=find]`MongoCollection#find` method is invoked to retrieve a `FindIterable<TDocument>` generic using the `Document` type, an iterable for all the crew members documents in the collection. The documents are [hotspot=iterate]`iterated` through and appended together into a String array to be returned.

Test the `READ` operation from the OpenAPI UI at the `GET /api/crew` enpoint.

This will retrieve all crew member documents from the collection.

You will receive a response containing an array of all the members currently in your crew.

```
[
  {
    "_id": {
      "$oid": "<<ID>>"
    },
    "Name": "Member1",
    "Rank": "Officer",
    "CrewID": "000001"
  }
]
```

=== Update

The [hotspot=update]`update()` method handles the implementation of `UPDATE`. Firstly the `Crew` collection is retrieved using [hotspot=getCollectionRead]`MongoDatabase.getCollection()`. Then, a [hotspot=queryUpdate]`Document` is created using the [hotspot=objectIdUpdate]`object id` to query the collection for the document. Next, a new crew member [hotspot=crewMemberUpdate]`Document` is created using the updated configuration. The [hotspot=replaceOne]`MongoCollection.replaceOne()` method is called with the query and new crew member document which will update all matching queries with the supplied document. Since the object id is unique in the collection, only one document will be updated. The [hotspot=replaceOne]`MongoCollection.replaceOne()` method will return an `UpdateResult`. The [hotspot=getMatchedCount]`UpdateResult.getMatchedCount()` method is invoked to determine the number of documents that matched the query. If the match count is 0, then the object id does not exist.

Test the `UPDATE` operation from the OpenAPI UI at the `PUT /api/crew/\{id\}` endpoint by specifying the `\<<ID>>` you saved from the `CREATE` section in the id parameter and setting the request body as:
```
{
  "name": "Member1",
  "rank": "Captain",
  "crewID": "000001"
}
```

This will update the rank of the crew member you created in the `CREATE` step from Officer to Captain.

You will receive a reponse containing the JSON object of the updated member.

```
{
  "_id": {
    "$oid": "<<ID>>"
  },
  "Name": "Member1",
  "Rank": "Captain",
  "CrewID": "000001"
}
```

=== Delete

The [hotspot=remove]`remove()` method handles the implementation of `DELETE`. Firstly the `Crew` collection is retrieved using [hotspot=getCollectionDelete]`MongoDatabase.getCollection()`. The [hotspot=deleteOne]`MongoCollection.DeleteOne()` method is called with a [hotspot=objectIdDelete]`Document` containing the `object id` to delete the matching document from the collection. The [hotspot=deleteOne]`MongoCollection.DeleteOne()` will return a `DeleteResult`. The [hotspot=getDeletedCount]`DeleteResult.getDeletedCount()` method is invoked to determine the number of documents that were deleted. If the deleted count is 0, then the object id does not exist.

Test the `DELETE` operation from the OpenAPI UI at the `DELETE /api/crew/\{id\}` endpoint by specifying the `\<<ID>>` you saved from `CREATE` section in the id parameter.

This will remove the document containing the specified crew member object id from the collection.

You will receive a response containing the object id of the deleted crew member.

```
{
  "_id": {
    "$oid": "<<ID>>"
  }
}
```

// =================================================================================================
// Running the microservice
// =================================================================================================

== Running the microservice

The Open Liberty server was started in development mode at the beginning of the guide and all the 
changes were automatically picked up.

If you see `The MongoServer server is ready to run a smarter planet. The MongoServer server started in 4.300 seconds.` in the console, then it is ready for you to check out the microservice that you created at the http://localhost:9080/mongo/[^] URL. 

// =================================================================================================
// Testing the service
// =================================================================================================

== Testing the service

You can test this microservice manually by starting a server and sending HTTP requests to http://localhost:9080/mongo/api/crew/[^] or by using the web interface at the http://localhost:9080/mongo/[^] URL. Automated tests are a much better
approach because they trigger a failure if a change introduces a bug. The JUnit and the JAX-RS Client
API provide a simple environment to test the microservice.

You can write tests to call the microservice server directly.

[role="code_command hotspot", subs="quotes"]
----
#Create the `CrewServiceIT` class.#
`src/test/java/it/io/openliberty/guides/application/CrewServiceIT.java`
----

CrewServiceIT.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/test/java/it/io/openliberty/guides/application/CrewServiceIT.java[]
----

The test methods are annotated with the [hotspot=test1 hotspot=test2 hotspot=test3 hotspot=test4 file=0]`@Test` annotation.

pom.xml
[source , xml, linenums,role="code_column hide_tags=copyright"]
----
include::finish/pom.xml[]
----

The test code needs to know some information about the microservice to make requests. The server port and the microservice context root are key, and are dictated by the server configuration. While this information can be hardcoded, it is better to specify it in a single place like the Maven [hotspot=defaultHttpPort hotspot=appContextRoot file=1]`pom.xml` file. Refer to the [hotspot file=1]`pom.xml` file to see how the microservice information such as the [hotspot=defaultHttpPort file=1]`http.port` and [hotspot=appContextRoot file=1]`default.app.context.root` elements are provided in the file.


These Maven properties are then passed to the Java test program as the [hotspot=testsysprops file=1]`<systemPropertyVariables/>` element in the [hotspot file=1]`pom.xml` file.

The [hotspot=Before file=0]`@BeforeAll` annotation is placed on a method that runs before any of the test cases. In this case, the method first creates a JAX-RS client, which will be used to make HTTP requests to the crew service. Then, it retrieves the port number and microservice context for the Open Liberty server to build a base URL string that is used throughout the tests. Lastly, it creates test data for the crew members.

The [hotspot=After file=0]`@AfterAll` with [hotspot=teardown file=0]`teardown()` method simply closes the client instance.

See the following descriptions of the test cases:

* [hotspot=testAddCrewMember file=0]`testAddCrewMember()` verifies that new members are correctly added to the database.

* [hotspot=testUpdateCrewMember file=0]`testUpdateCrewMember()` verifies that a crew member information is correctly updated.

* [hotspot=testGetCrewMembers file=0]`testGetCrewMembers()` verifies that a list of crew members returned by the microservice API.

* [hotspot=testDeleteCrewMember file=0]`testDeleteCrewMember()` verifies that the crew members are correctly removed from the database.

[role='command']
include::{common-includes}/devmode-test.adoc[]

You will see the following output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.application.CrewServiceIT
   === Adding 2 crew members to the database. ===
      === Done. ===
   === Updating crew member with id 5df8e0a004ccc019976c7d0a. ===
      === Done. ===
   === Listing crew members from the database. ===
      === Done. There are 2 crew members. ===
   === Removing 2 crew members from the database. ===
      === Done. ===
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.411 s - in it.io.openliberty.guides.application.CrewServiceIT
Results:
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, add an assertion that you know fails, or change the existing
[hotspot=assertEquals file=0]`assertEquals` method to expect `301` instead of `200`.

[role='command']
include::{common-includes}/devmode-quit.adoc[]


== Great work! You're done!

You developed a microservice in Open Liberty by using MongoDB, JAX-RS and JSON-B.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]