//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: mongodb-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2019-12-12
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to access MongoDB by using Contexts and Dependency Injection (CDI), and configure MongoDB through MicroProfile Config.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE', 'MongoDB']
:page-related-guides: ['cdi-intro', 'microprofile-config', 'rest-intro']
:page-permalink: /guides/{projectid}
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:page-seo-title: Accessing MongoDB by using Contexts and Dependency Injection (CDI)
:page-seo-description: Learn how to access MongoDB by using Contexts and Dependency Injection (CDI), and configure MongoDB through MicroProfile Config.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Accessing MongoDB by using Contexts and Dependency Injection (CDI)

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to access MongoDB by using Contexts and Dependency Injection (CDI), and configure MongoDB through MicroProfile Config.

== What you'll learn

You will learn how to build and test a simple microservice which manages the members of a crew using `MongoDB`. The microservice will respond to `POST`, `GET`, `PUT`, and `DELETE` requests made to the service to manipulate the database.

The crew members will be stored in `MongoDB` as documents in the following JSON-like format:

[source,json,role="no_copy"]
----
{
  "_id": {
    "$oid": "5dee6b079503234323db2ebc"
  },
  "Name": "Member1",
  "Rank": "Captain",
  "CrewID": "000001"
}
----

This microservice connects to `MongoDB` using Transport Layer Security (TLS) and injects a `MongoDatabase` instance into the service through a CDI producer.  Additionally, MicroProfile Config is used to easily configure the `MongoDB` driver.

For more information about CDI and MicroProfile Config, see https://openliberty.io/guides/cdi-intro.html[Injecting dependencies into microservices^] and https://openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices^].

// =================================================================================================
// Additional Prerequisites
// =================================================================================================

== Additional Prerequisites

You will be using Docker to run an instance of `MongoDB` for a fast installation and setup. Install Docker by following the instructions on the official https://docs.docker.com/engine/installation[Docker documentation^] and start your Docker environment.

// =================================================================================================
// Getting Started
// =================================================================================================

[role='command']
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Setting up MongoDB
// =================================================================================================

== Setting up MongoDB

This guide uses Docker to run an instance of `MongoDB`. A multi-stage Dockerfile is provided which uses the `mongo` image as the final stage's base image and will gather the required configuration files. Then, the resulting `mongo` image will run in a Docker container and you will need to setup a new database for the microservice. Lastly, the truststore generated in the Docker image will be copied from the container and placed into the Open Liberty server.

**The MongoDB configuration**

mongodb.conf
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::assets/mongodb.conf[]
----

The `mongodb.conf` file specifies the `MongoDB` configuration that the `MongoDB` daemon should use. A sample configuration file is provided which sets up the [hotspot=storage file=0]`storage`, [hotspot=systemLog file=0]`systemLog`, and [hotspot=net file=0]`net` options for this application. Additional details and other configuration options can be found in the official https://docs.mongodb.com/manual/reference/configuration-options/[MongoDB website^].

**The Dockerfile**

Dockerfile
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::assets/Dockerfile[]
----

index.js
[source,javascript,linenums,role="code_column hide_tags=copyright"]
----
include::assets/index.js[]
----

The [hotspot=stageOne file=1]`first stage` of the Dockerfile uses the [hotspot=openLiberty file=1]`adoptopenjdk/openjdk8-openj9:ubi` image as the base image to create a [hotspot=selfSignedCert file=1]`self-signed certificate` and [hotspot=privateKey file=1]`private key` which are concatenated together to generate the [hotspot=catCerts file=1]`mongodb_tls.pem` file used for TLS. Then, it uses the Java [hotspot=keytool file=1]`keytool` to generate the truststore and adds the certificate file to the truststore.

The [hotspot=stageTwo file=1]`second stage` of the Dockerfile uses the [hotspot=mongo file=1]`mongo` image as the base image and copies over the generated files from the [hotspot=stageOne hotspot=copyCerts file=1]`first stage`. Additionally, it copies the [hotspot=copyConfig file=1]`mongodb.conf` configuration file and the [hotspot=copyJS file=1]`index.js` script from your host machine to the image. Then, it runs [hotspot=runMongod file=1]`mongod` to start the `MongoDB` daemon and runs [hotspot=runScript file=1]`mongo` to execute the [hotspot=script file=1]`index.js` script. This script creates a new [hotspot=createUser file=2]`user` and [hotspot=createCollection file=2]`collection` in the database. The `MongoDB` daemon is then [hotspot=shutdown file=1]`shutdown`. Lastly, the [hotspot=cmd file=1]`CMD` command is used to start the `MongoDB` daemon using the `mongodb.conf` configuration file when the image is run in a container.

For additional information about the `mongo` image, see https://hub.docker.com/_/mongo[mongo^].

**Running MongoDB in a Docker container**

Execute the following commands to build the image using the Dockerfile, run it in a Docker container, and map port `27017` from the container to your host machine:

[role='command']
```
docker build -t mongo-sample -f assets/Dockerfile .
docker run --name mongo-guide -p 27017:27017 -d mongo-sample
```

**Adding the truststore to the Open Liberty server**

The truststore created in the container needs to be added to the Open Liberty server, so the server can trust the certificate `MongoDB` presents when they are connecting. Execute the following command to copy the `truststore.p12` file from the container to the correct folder in the start and finish directories on your host machine:

include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section]
--
[role='command']
```
docker cp ^
  mongo-guide:/home/mongodb/certs/truststore.p12 ^
  start/src/main/liberty/config/resources/security
docker cp ^
  mongo-guide:/home/mongodb/certs/truststore.p12 ^
  finish/src/main/liberty/config/resources/security
```
--

[.tab_content.mac_section]
--
[role='command']
```
docker cp \
  mongo-guide:/home/mongodb/certs/truststore.p12 \
  start/src/main/liberty/config/resources/security
docker cp \
  mongo-guide:/home/mongodb/certs/truststore.p12 \
  finish/src/main/liberty/config/resources/security
```
--

[.tab_content.linux_section]
--
[role='command']
```
docker cp \
  mongo-guide:/home/mongodb/certs/truststore.p12 \
  start/src/main/liberty/config/resources/security
docker cp \
  mongo-guide:/home/mongodb/certs/truststore.p12 \
  finish/src/main/liberty/config/resources/security
```
--

// =================================================================================================
// Try what you'll build
// =================================================================================================

== Try what you'll build

The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.

To try out the application, first go to the `finish` directory and run the following
Maven goal to build the application and deploy it to Open Liberty:

[role='command']
```
mvn liberty:run
```

After you see the following message, your application server is ready.

[role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----

Check out the service at the
http://localhost:9080/mongo/[^] URL. 

[role='command']
include::{common-includes}/twyb-end.adoc[]

// =================================================================================================
// Configuring the Open Liberty Server
// =================================================================================================

== Configuring the Open Liberty Server

Navigate to the `start` directory to begin.

To create a CDI producer for `MongoDB` and connect over TLS, the Open Liberty server needs to be correctly configured.

[role="code_command hotspot", subs="quotes"]
----
#Create the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

pom.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/pom.xml[]
----

The features required to create the CDI producer for `MongoDB` are [hotspot=cdiFeature file=0]`cdi-2.0`, [hotspot=sslFeature file=0]`ssl-1.0`, [hotspot=mpConfigFeature file=0]`mpConfig-1.4`, and [hotspot=passwordUtilFeature file=0]`passwordUtilities-1.0` which are specified in the [hotspot=featureManager file=0]`featureManager` element. In the past, using `MongoDB` required enabling the `mongodb-2.0` feature, which was limited to certain `MongoDB` 2.x versions. By using a CDI producer, any version of MongoDB can be used, with no need for a specific `MongoDB` feature. Even if the `MongoDB` Java Driver API changes, simple updates to your CDI producer will allow it to continue to work. The `MongoDB` driver is bundled in your microservice in your [hotspot=mongoDriver file=1]`pom.xml`.

Additionally, the Secure Sockets Layer (SSL) context is configured in the [hotspot file=0]`server.xml` so the application can connect to `MongoDB` using TLS. The [hotspot=keyStore file=0]`keyStore` element is configured with an `id` of `outboundTrustStore` to point to the `truststore.p12` keystore file created in one of the earlier sections with the password of `mongodb` and type of `PKCS12`. The [hotspot=ssl file=0]`ssl` element is configured with an id of `outboundSSLContext` to use the `defaultKeyStore` as the keystore, `outboundTrustStore` as the truststore, and `TLS` as the SSL protocol. 

// =================================================================================================
// Starting the Open Liberty server in development mode
// =================================================================================================

== Starting the Open Liberty server in development mode

[role='command']
include::{common-includes}/devmode-start.adoc[]

// =================================================================================================
// Configuring with MicroProfile Config
// =================================================================================================

== Configuring with MicroProfile Config

Using MicroProfile Config makes configuring the `MongoDB` driver simple since all the configuration can be set in one place and injected into the CDI producer.

[role="code_command hotspot", subs="quotes"]
----
#Create the configuration file.#
`src/main/webapp/META-INF/microprofile-config.properties`
----

microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/webapp/META-INF/microprofile-config.properties[]
----

Properties such as the [hotspot=hostname file=0]`hostname`, [hotspot=port file=0]`port`, and [hotspot=dbname file=0]`database name` for the running `MongoDB` instance are set. Additionally, the user's [hotspot=mongoUser file=0]`username` and [hotspot=passEncoded file=0]`password` are set here. For added security, the password was encoded using `securityUtility`.

For reference on how the encoded password was generated, navigate to the `target/liberty/wlp/bin/` directory in a separate command-line session and run the following command:

--
[role='command']
```
./securityUtility encode openliberty --encoding=aes
```
--

This generates an Advanced Encryption Standard (AES) encoding of the password `openliberty`.

// =================================================================================================
// Creating a CDI Producer for Mongo
// =================================================================================================

== Creating a CDI Producer for Mongo

With a CDI producer, you are no longer restricted to `MongoDB` 2.x versions, and can easily provide a `MongoDatabase` to your microservice.

[role="code_command hotspot", subs="quotes"]
----
#Create the `MongoProducer` class.#
`src/main/java/io/openliberty/guides/mongo/MongoProducer.java`
----

MongoProducer.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/mongo/MongoProducer.java[]
----

microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/webapp/META-INF/microprofile-config.properties[]
----

pom.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/pom.xml[]
----

server.xml
[source,xml,linenums,role="code_column hide_tags=copyright"]
----
include::finish/src/main/liberty/config/server.xml[]
----

This class contains a producer method for the `MongoClient`, a producer method for the `MongoDatabase` which uses the `MongoClient` producer method, and a dispose method for the `MongoClient`.

Before creating the methods, the values in the [hotspot file=1]`microprofile-config.properties` file are injected into the [hotspot=mongoProducerInjections file=0]`MongoProducer` class. 

The [hotspot=createMongo file=0]`createMongo()` method is annotated with [hotspot=produces1 file=0]`@Produces` and returns an instance of `MongoClient`. Firstly, the function decodes the encoded password using the [hotspot=decode file=0]`PasswordUtil.passwordDecode()` method from the [hotspot=passwordUtilFeature file=3]`passwordUtilities-1.0` feature. Then, the [hotspot=username file=0]`username`, [hotspot=dbName file=0]`database name`, and [hotspot=password file=0]`decoded password` are passed into the [hotspot=createCredential file=0]`MongoCredential.createCredential()` method to get an instance of `MongoCredential`. The [hotspot=sslContext file=0]`JSSEHelper` is used to get the `SSLContext` from the [hotspot=outboundSSLContext file=0]`outboundSSLContext` created in the [hotspot=ssl file=3]`server.xml`. Lastly, a [hotspot=mongoClient file=0]`MongoClient` instance is created and returned. The [hotspot=mongoClient file=0]`MongoClient` instance was created using an instance of [hotspot=serverAddress file=0]`ServerAddress` which contains the hostname and port, the [hotspot=creds file=0]`MongoCredential` instance, and an instance of [hotspot=optionsBuilder file=0]`MongoClientOptions` which enables SSL and specifies the SSL context.

The [hotspot=createDB file=0]`createDB()` method is annotated with [hotspot=produces2 file=0]`@Produces` and returns an instance of `MongoDatabase`. The method injects the [hotspot=injectMongoClient file=0]`MongoClient` in its parameters and invokes the [hotspot=getDatabase file=0]`MongoClient.getDatabase()` method, passing in the database name to get the `MongoDatabase` instance. The [hotspot=getDatabase file=0]`MongoDatabase` instance is returned.

The [hotspot=close file=0]`close()` method is a cleanup function for the `MongoClient`. The method injects the `MongoClient` in its parameters, annotated with [hotspot=disposes file=0]`@Disposes`. The [hotspot=toClose file=0]`MongoClient.close()` method is invoked to close the connection to the `MongoDB` instance.

// =================================================================================================
// Implementing CRUD operations
// =================================================================================================

== Implementing CRUD operations

You will be implementing the basic `CRUD` operations which are `CREATE`, `READ`, `UPDATE`, and `DELETE`. The [hotspot=mongoImports1]`com.mongodb.client` and [hotspot=mongoImports2]`com.mongodb.client.result` packages are used to help implement these `CRUD` operations for the microservice. For more information about these packages, see the https://mongodb.github.io/mongo-java-driver/3.12/javadoc/com/mongodb/client/package-summary.html[com.mongodb.client^] and https://mongodb.github.io/mongo-java-driver/3.12/javadoc/com/mongodb/client/result/package-summary.html[com.mongodb.client.result^] Javadocs.

See https://openliberty.io/guides/rest-intro.html[Creating a RESTful web serivce^] for more information about creating a REST service with JAX-RS, JSON-B, and Open Liberty.

[role="code_command hotspot", subs="quotes"]
----
#Replace the `CrewService` class.#
`src/main/java/io/openliberty/guides/application/CrewService.java`
----

CrewService.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/application/CrewService.java[]
----

CrewMember.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/main/java/io/openliberty/guides/application/CrewMember.java[]
----

A [hotspot=beanValidator]`Validator` is used to validate the [hotspot=crewMember file=1]`CrewMember` using the [hotspot=getViolations]`getViolations()` method before [hotspot=violations1]`inserting` or [hotspot=violations2]`updating` the database.

**Injecting the database**

The CDI producer is used to inject a [hotspot=dbInjection]`MongoDatabase` into the [hotspot file=0]`CrewService` class.

Visit the http://localhost:9080/openapi/ui/[^] URL to view the OpenAPI UI which provides API documentation and a client to test the API endpoints you will create.

=== Creating a crew member

The [hotspot=add]`add()` method handles the implementation of `CREATE`. An instance of `MongoCollection` is retrieved by invoking [hotspot=getCollection]`MongoDatabase.getCollection()` method and specifying the `Crew` collection. The `MongoCollection<TDocument>` is a generic with a `TDocument` type parameter. The `TDocument` type parameter specifies the document type used to store data in the `MongoCollection`. The [hotspot=bsonDocument]`Document` class will be used as the `TDocument` type for this guide. The crew member is converted to a [hotspot=crewMemberCreation]`Document` and the [hotspot=insertOne]`MongoCollection.insertOne()` method is called to insert the new crew member `Document`.

Test the `CREATE` operation through the OpenAPI UI at the `POST /api/crew` endpoint with the following as the request body:

[role='command']
```
{
  "name": "Member1",
  "rank": "Officer",
  "crewID": "000001"
}
```

This will create a new document in the `Crew` collection with a Name of `Member1`, Rank of `Officer`, and CrewID of `000001`.

You will receive a response containing the JSON object of the new member.

[role="no_copy"]
```
{
  "_id": {
    "$oid": "<<ID>>"
  },
  "Name": "Member1",
  "Rank": "Officer",
  "CrewID": "000001"
}
```

The `\<<ID>>` is a unique identifier in the collection. Save this value for future commands.

=== Reading all crew members

The [hotspot=retrieve]`retrieve()` method handles the implementation of `READ`. Firstly the `Crew` collection is retrieved using [hotspot=getCollectionRead]`MongoDatabase.getCollection()`. The [hotspot=find]`MongoCollection.find()` method is invoked to retrieve a `FindIterable<TDocument>` generic using the `Document` type, an iterable for all the crew members documents in the collection. The documents are [hotspot=iterate]`iterated` through and appended together into a String array to be returned.

Test the `READ` operation from the OpenAPI UI at the `GET /api/crew` endpoint.

This will retrieve all crew member documents from the collection.

You will receive a response containing an array of all the members currently in your crew. The response may include crew members created in the **Try what you'll build** section.

[role="no_copy"]
```
[
  {
    "_id": {
      "$oid": "<<ID>>"
    },
    "Name": "Member1",
    "Rank": "Officer",
    "CrewID": "000001"
  }
]
```

=== Updating a crew member

The [hotspot=update]`update()` method handles the implementation of `UPDATE`. Firstly, the `Crew` collection is retrieved using [hotspot=getCollectionUpdate]`MongoDatabase.getCollection()`. Then, a [hotspot=queryUpdate]`Document` is created using the [hotspot=objectIdUpdate]`object id` to be used to query the collection for the document containing the specified object id. Next, a new crew member [hotspot=crewMemberUpdate]`Document` is created using the updated configuration. The [hotspot=replaceOne]`MongoCollection.replaceOne()` method is called with the query and new crew member document which will update all matching queries with the supplied document. Since the object id is unique in the collection, only one document will be updated. The [hotspot=replaceOne]`MongoCollection.replaceOne()` method will return an `UpdateResult`. The [hotspot=getMatchedCount]`UpdateResult.getMatchedCount()` method is invoked to determine the number of documents that matched the query. If the match count is 0, then the object id does not exist.

Test the `UPDATE` operation from the OpenAPI UI at the `PUT /api/crew/\{id\}` endpoint by specifying the `\<<ID>>` you saved from the `CREATE` section in the id parameter and setting the request body as:

[role='command']
```
{
  "name": "Member1",
  "rank": "Captain",
  "crewID": "000001"
}
```

This will update the rank of the crew member you created in the `CREATE` step from Officer to Captain.

You will receive a reponse containing the JSON object of the updated member.

[role="no_copy"]
```
{
  "_id": {
    "$oid": "<<ID>>"
  },
  "Name": "Member1",
  "Rank": "Captain",
  "CrewID": "000001"
}
```

=== Deleting a crew member

The [hotspot=remove]`remove()` method handles the implementation of `DELETE`. Firstly, the `Crew` collection is retrieved using [hotspot=getCollectionDelete]`MongoDatabase.getCollection()`. Then, a [hotspot=queryDelete]`Document` is created using the [hotspot=objectIdDelete]`object id` to be used to query the collection for the document containing the specified object id. The [hotspot=deleteOne]`MongoCollection.deleteOne()` method is called with the query. Since the object id is unique in the collection, only one document will be deleted. The [hotspot=deleteOne]`MongoCollection.deleteOne()` will return a `DeleteResult`. The [hotspot=getDeletedCount]`DeleteResult.getDeletedCount()` method is invoked to determine the number of documents that were deleted. If the deleted count is 0, then the object id does not exist.

Test the `DELETE` operation from the OpenAPI UI at the `DELETE /api/crew/\{id\}` endpoint by specifying the `\<<ID>>` you saved from `CREATE` section in the id parameter.

This will remove the document containing the specified crew member object id from the collection.

You will receive a response containing the object id of the deleted crew member.

[role="no_copy"]
```
{
  "_id": {
    "$oid": "<<ID>>"
  }
}
```

// =================================================================================================
// Running the microservice
// =================================================================================================

[role='command']
include::{common-includes}/devmode-build.adoc[]

If you see something similar to `The application guide-mongodb-intro updated in 1.023 seconds.` in the console, then it is ready for you to check out the microservice that you created at the http://localhost:9080/mongo/[^] URL. 

// =================================================================================================
// Testing the service
// =================================================================================================

== Testing the service

You will create integrated tests to ensure the basic functionality of the `crew` service.

[role="code_command hotspot", subs="quotes"]
----
#Create the `CrewServiceIT` class.#
`src/test/java/it/io/openliberty/guides/application/CrewServiceIT.java`
----

CrewServiceIT.java
[source, Java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/src/test/java/it/io/openliberty/guides/application/CrewServiceIT.java[]
----

The test methods are annotated with the [hotspot=test1 hotspot=test2 hotspot=test3 hotspot=test4 file=0]`@Test` annotation.

See the following descriptions of the test cases:

* [hotspot=testAddCrewMember file=0]`testAddCrewMember()` verifies that new members are correctly added to the database.

* [hotspot=testUpdateCrewMember file=0]`testUpdateCrewMember()` verifies that a crew member's information is correctly updated.

* [hotspot=testGetCrewMembers file=0]`testGetCrewMembers()` verifies that a list of crew members is returned by the microservice API.

* [hotspot=testDeleteCrewMember file=0]`testDeleteCrewMember()` verifies that the crew members are correctly removed from the database.

[role='command']
include::{common-includes}/devmode-test.adoc[]

You will see the following output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.application.CrewServiceIT
   === Adding 2 crew members to the database. ===
      === Done. ===
   === Updating crew member with id 5df8e0a004ccc019976c7d0a. ===
      === Done. ===
   === Listing crew members from the database. ===
      === Done. There are 2 crew members. ===
   === Removing 2 crew members from the database. ===
      === Done. ===
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.411 s - in it.io.openliberty.guides.application.CrewServiceIT
Results:
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

== Tearing down the environment

[role='command']
include::{common-includes}/devmode-quit.adoc[]

Then, execute the following commands to stop and remove the `mongo-guide` container, and to remove the `mongo-sample` and `mongo` images.

[role='command']
```
docker stop mongo-guide
docker rm mongo-guide
docker rmi mongo-sample
docker rmi mongo
```

== Great work! You're done!

You developed a microservice in Open Liberty by using MongoDB, CDI, MicroProfile Config, and JAX-RS.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
